"""
AeroResolve Scenarios Specification
Hard-coded deterministic scenario definitions for reproducible demonstration.
"""

from typing import Dict, Any, List

SCENARIOS: List[Dict[str, Any]] = [
    {
        "scenario_id": "SCEN-01-GHOST-FAULT",
        "scenario_name": "Ghost Fault: Intermittent High-Altitude / Low-Temperature Avionics Warning",
        "aircraft_id": "ABR-017",
        "target_flight_number": "AB-402",
        "route": "BLR-DEL",
        "injected_defect_type": "INTERMITTENT_HARNESS_MICRO_FRETTING",
        "true_root_cause": "Wiring harness connector pin micro-fretting corrosion on connector X42 in avionics rack extraction circuit",
        "environmental_trigger": {
            "min_altitude_ft": 32000,
            "max_oat_c": -42.0,
            "min_vibration_index": 1.15,
            "min_flight_duration_mins": 45
        },
        "is_ghost_fault": True,
        "prior_recurrence_count": 3,
        "expected_destination_station": "DEL",
        "expected_missing_part": "PART-X42-CONN",
        "expected_reposition_source": "BOM",
        "healthy_control_case": False,
        "false_hypothesis": "Avionics Ventilation & Cooling Computer (AVCC) Internal Board Failure",
        "why_false_hypothesis_fails": "AVCC was already reset 12 days prior and completely replaced 5 days prior at BOM; defect returned identically under vibration and cold temperature.",
        "expected_agent_sequence": [
            {"order": 1, "agent": "HEALTH_AGENT", "action": "DETECT_ANOMALY", "min_conf": 0.85},
            {"order": 2, "agent": "REPEAT_DEFECT_AGENT", "action": "RECALL_PRIOR_ACTIONS", "min_conf": 0.90},
            {"order": 3, "agent": "ROOT_CAUSE_AGENT", "action": "RETRIEVE_CORTEX_EVIDENCE", "min_conf": 0.88},
            {"order": 4, "agent": "GROUND_READINESS_AGENT", "action": "CHECK_INVENTORY_AND_ROSTER", "min_conf": 0.95},
            {"order": 5, "agent": "OPERATIONS_IMPACT_AGENT", "action": "SIMULATE_BLAST_RADIUS", "min_conf": 0.90},
            {"order": 6, "agent": "AERORESOLVE_ORCHESTRATOR", "action": "SYNTHESIZE_RECOMMENDATION", "min_conf": 0.89}
        ]
    },
    {
        "scenario_id": "SCEN-02-REPEAT-DEFECT",
        "scenario_name": "Repeated Defect & Ineffective Repair Loop",
        "aircraft_id": "ABR-017",
        "target_flight_number": "AB-402",
        "route": "BLR-DEL",
        "injected_defect_type": "INEFFECTIVE_COMPONENT_SWAP",
        "true_root_cause": "Intermittent contact resistance in rack receptacle pin 4 causing simulated fan flow alarm",
        "environmental_trigger": {"min_altitude_ft": 30000},
        "is_ghost_fault": True,
        "prior_recurrence_count": 2,
        "expected_destination_station": "DEL",
        "expected_missing_part": "PART-X42-CONN",
        "expected_reposition_source": "BOM",
        "healthy_control_case": False,
        "false_hypothesis": "Faulty cooling fan motor",
        "why_false_hypothesis_fails": "Cooling fan current signature normal on ground; failure occurs only in turbulent cold cruise envelope.",
        "expected_agent_sequence": []
    },
    {
        "scenario_id": "SCEN-03-SILENT-DEGRADATION",
        "scenario_name": "Silent Degradation: 20-Sector Avionics Fan Current Creep",
        "aircraft_id": "ABR-017",
        "target_flight_number": "AB-402",
        "route": "BLR-DEL",
        "injected_defect_type": "GRADUAL_CURRENT_DRIFT",
        "true_root_cause": "Impedance drift and pin oxidation causing current draw increase from 3.2A to 4.7A across 20 flights",
        "environmental_trigger": {"min_altitude_ft": 20000},
        "is_ghost_fault": False,
        "prior_recurrence_count": 0,
        "expected_destination_station": "DEL",
        "expected_missing_part": "PART-X42-CONN",
        "expected_reposition_source": "BOM",
        "healthy_control_case": False,
        "false_hypothesis": "Normal aging tolerance",
        "why_false_hypothesis_fails": "Rate of change is 4.8x fleet average degradation slope.",
        "expected_agent_sequence": []
    },
    {
        "scenario_id": "SCEN-04-DESTINATION-NOT-READY",
        "scenario_name": "Destination Station Missing Spare Part",
        "aircraft_id": "ABR-017",
        "target_flight_number": "AB-402",
        "route": "BLR-DEL",
        "injected_defect_type": "SPARE_PART_STOCKOUT_AT_DESTINATION",
        "true_root_cause": "DEL inventory for PART-X42-CONN is 0 units; BOM has 3 serviceable units in stock",
        "environmental_trigger": {},
        "is_ghost_fault": False,
        "prior_recurrence_count": 0,
        "expected_destination_station": "DEL",
        "expected_missing_part": "PART-X42-CONN",
        "expected_reposition_source": "BOM",
        "healthy_control_case": False,
        "false_hypothesis": "Wait for aircraft to land and ground engineer to manually check warehouse shelf",
        "why_false_hypothesis_fails": "Waiting until block arrival causes 120-minute turnaround delay and missed onward international sector.",
        "expected_agent_sequence": []
    },
    {
        "scenario_id": "SCEN-05-NETWORK-BLAST-RADIUS",
        "scenario_name": "Downstream Flight Propagation & Passenger Disruption",
        "aircraft_id": "ABR-017",
        "target_flight_number": "AB-501",  # Downstream flight DEL -> DXB
        "route": "DEL-DXB",
        "injected_defect_type": "SCHEDULE_ROTATION_EXPOSURE",
        "true_root_cause": "115 minute unscheduled turnaround maintenance triggers international departure curfew and connection cascade",
        "environmental_trigger": {},
        "is_ghost_fault": False,
        "prior_recurrence_count": 0,
        "expected_destination_station": "DEL",
        "expected_missing_part": "PART-X42-CONN",
        "expected_reposition_source": "BOM",
        "healthy_control_case": False,
        "false_hypothesis": "Delay impact is confined to single flight",
        "why_false_hypothesis_fails": "Downstream flight DEL-DXB has 42 passengers connecting to European and American long-haul flights.",
        "expected_agent_sequence": []
    },
    {
        "scenario_id": "SCEN-06-REPAIR-VERIFICATION",
        "scenario_name": "Post-Repair Flight Telemetry Surveillance",
        "aircraft_id": "ABR-017",
        "target_flight_number": "AB-501",
        "route": "DEL-DXB",
        "injected_defect_type": "POST_REPAIR_SURVEILLANCE",
        "true_root_cause": "Repair using connector kit PART-X42-CONN completely normalized circuit impedance and cleared defect signature",
        "environmental_trigger": {},
        "is_ghost_fault": False,
        "prior_recurrence_count": 0,
        "expected_destination_station": "DXB",
        "expected_missing_part": None,
        "expected_reposition_source": None,
        "healthy_control_case": False,
        "false_hypothesis": "Assume repair was successful without subsequent flight surveillance",
        "why_false_hypothesis_fails": "Component swaps in prior weeks appeared successful on ground but failed at 34,000 ft.",
        "expected_agent_sequence": []
    },
    {
        "scenario_id": "SCEN-07-FLEET-LEARNING",
        "scenario_name": "Fleet Precedent Retrieval for Similar Emerging Signature",
        "aircraft_id": "ABR-042",
        "target_flight_number": "AB-703",
        "route": "BOM-CCU",
        "injected_defect_type": "SIMILAR_SIGNATURE_EMERGENCE",
        "true_root_cause": "Connector pin micro-fretting on sister aircraft ABR-042 matching resolved case ABR-017",
        "environmental_trigger": {"min_altitude_ft": 31000},
        "is_ghost_fault": True,
        "prior_recurrence_count": 1,
        "expected_destination_station": "CCU",
        "expected_missing_part": "PART-X42-CONN",
        "expected_reposition_source": "BOM",
        "healthy_control_case": False,
        "false_hypothesis": "Replace computer on ABR-042",
        "why_false_hypothesis_fails": "Case memory demonstrates computer replacement was ineffective on ABR-017; harness pin service resolved issue.",
        "expected_agent_sequence": []
    },
    {
        "scenario_id": "SCEN-08-HEALTHY-CONTROL",
        "scenario_name": "Healthy Control Flight with Elevated Turbulence",
        "aircraft_id": "ABR-009",
        "target_flight_number": "AB-308",
        "route": "HYD-DEL",
        "injected_defect_type": "BENIGN_TRANSIENT_SPIKE",
        "true_root_cause": "Transient meteorological turbulence without hardware degradation",
        "environmental_trigger": {},
        "is_ghost_fault": False,
        "prior_recurrence_count": 0,
        "expected_destination_station": "DEL",
        "expected_missing_part": None,
        "expected_reposition_source": None,
        "healthy_control_case": True,
        "false_hypothesis": "Raise high-priority AOG maintenance alert",
        "why_false_hypothesis_fails": "All baseline signals returned to nominal mean immediately after turbulence patch; no repeat defect in history.",
        "expected_agent_sequence": []
    }
]
